"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type FileState = { file: File | null; error?: string; preview?: { count?: number; fields?: string[] } };
const MAX_BYTES = 2 * 1024 * 1024;

export default function NewMigrationPage() {
  const router = useRouter();
  const api = process.env.NEXT_PUBLIC_API_URL ?? "https://backend-eight-sable-88.vercel.app";
  const [sourceSchema, setSourceSchema] = useState<FileState>({ file: null });
  const [targetSchema, setTargetSchema] = useState<FileState>({ file: null });
  const [sourceRecords, setSourceRecords] = useState<FileState>({ file: null });
  const [name, setName] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const inspect = async (file: File, kind: "schema" | "records"): Promise<FileState> => {
    if (file.size > MAX_BYTES) return { file, error: "File must be 2 MB or smaller." };
    try { const text = await file.text(); const parsed = file.name.toLowerCase().endsWith(".csv") ? { count: Math.max(0, text.trim().split(/\r?\n/).length - 1) } : JSON.parse(text); if (kind === "schema") { if (!parsed || !Array.isArray(parsed.fields)) throw new Error("Schema must contain a fields array."); return { file, preview: { fields: parsed.fields.map((field: { name: string }) => field.name), count: parsed.fields.length } }; } if (!Array.isArray(parsed) && !file.name.toLowerCase().endsWith(".csv")) throw new Error("Records JSON must be an array."); return { file, preview: { count: Array.isArray(parsed) ? parsed.length : parsed.count } }; } catch (caught) { return { file, error: caught instanceof Error ? caught.message : "Unable to preview file." }; }
  };
  const choose = (setter: (state: FileState) => void, kind: "schema" | "records") => async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) setter(await inspect(file, kind)); };
  const ready = useMemo(() => [sourceSchema, targetSchema, sourceRecords].every((state) => state.file && !state.error), [sourceSchema, targetSchema, sourceRecords]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!ready) return; setBusy(true); setError(""); try { const body = new FormData(); body.append("sourceSchema", sourceSchema.file as File); body.append("targetSchema", targetSchema.file as File); body.append("sourceRecords", sourceRecords.file as File); if (name.trim()) body.append("name", name.trim()); const response = await fetch(`${api}/migrations`, { method: "POST", body }); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message ?? "Upload failed."); router.push(`/migrations/${data.migration.id}`); } catch (caught) { setError(caught instanceof Error ? caught.message : "Upload failed."); } finally { setBusy(false); } };
  const picker = (label: string, state: FileState, setter: (state: FileState) => void, kind: "schema" | "records", accept: string) => <label className="block cursor-pointer border border-[#d7d5cf] bg-white p-4 shadow-sm hover:border-[#167a5a]"><span className="font-mono text-[11px] font-semibold uppercase tracking-[0.14em] text-[#6b6b6b]">{label}</span><input className="mt-4 block w-full text-xs text-[#6b6b6b]" type="file" accept={accept} onChange={choose(setter, kind)} />{state.file && <p className="mt-3 truncate font-mono text-xs text-[#171717]">{state.file.name}</p>}{state.preview?.count !== undefined && <p className="mt-1 text-xs text-[#167a5a]">✓ {state.preview.count} {kind === "records" ? "records detected" : "fields detected"}</p>}{state.preview?.fields && <p className="mt-2 line-clamp-2 text-xs leading-5 text-[#8a8983]">{state.preview.fields.join(" · ")}</p>}{state.error && <p className="mt-2 text-xs text-[#b42318]">{state.error}</p>}</label>;
  return <main className="min-h-screen bg-[#f7f7f5] px-6 py-10 lg:px-10"><div className="mx-auto max-w-4xl"><Link href="/" className="font-mono text-xs text-[#6b6b6b] hover:text-[#167a5a]">← migrations</Link><div className="mt-8 border-b border-[#e7e5e0] pb-7"><p className="font-mono text-xs uppercase tracking-[0.18em] text-[#8a8983]">New migration</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Upload migration inputs</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#6b6b6b]">Provide a source schema, target schema, and bounded records. MigrateFlow will analyze the inputs before any human approval is requested.</p></div><form onSubmit={submit} className="mt-8 space-y-6"><label className="block max-w-xl"><span className="text-sm font-medium">Migration name <span className="font-normal text-[#8a8983]">optional</span></span><input value={name} onChange={(event) => setName(event.target.value)} className="mt-2 w-full border border-[#d7d5cf] bg-white px-3 py-2.5 text-sm shadow-sm placeholder:text-[#aaa8a1]" placeholder="Uploaded employee migration" /></label><div className="grid gap-4 md:grid-cols-3">{picker("Source schema", sourceSchema, setSourceSchema, "schema", ".json")}{picker("Target schema", targetSchema, setTargetSchema, "schema", ".json")}{picker("Source records", sourceRecords, setSourceRecords, "records", ".json,.csv")}</div>{error && <p className="border border-[#f0c9c5] bg-[#fff5f3] p-3 text-sm text-[#8f2119]">{error}</p>}<div className="flex items-center justify-between border-t border-[#e7e5e0] pt-5"><p className="font-mono text-xs text-[#8a8983]">JSON schemas · JSON array or CSV · max 1,000 records</p><button disabled={!ready || busy} className="rounded-md bg-[#171717] px-5 py-2.5 text-sm font-medium text-white hover:bg-[#30302e] disabled:opacity-40">{busy ? "Uploading…" : "Analyze migration"}</button></div></form></div></main>;
}
